---

# inclue of handlers is broken with Ansible 2.0.x, this is a work around
# e.g: https://github.com/ansible/ansible/issues/13485

# non-systemd
- name: reload tinc - default
  service:
    name: tinc
    state: "reloaded"
  become: yes
  become_method: sudo

- name: restart tinc - default
  service:
    name: tinc
    state: "restarted"
  become: yes
  become_method: sudo

# systemd
- name: reload tinc - systemd
  service:
    name: "tinc.service"
    state: reloaded
  become: yes
  become_method: sudo

- name: restart tinc - systemd
  service:
    name: "tinc.service"
    state: restarted
  become: yes
  become_method: sudo
